### ISSUE TITLE
Bor's Animal Crossing Update

### ISSUE THREAD

**Issue by GameBorAdvance** [WuBoytH/The-WuBor-Patch#31]
A payload of Bor updates before ver. 13.0 is finalized. Primarily concerns re-cloning Villager and Isabelle.
-Chrom's scale increase is being reduced to only 17/16 the size of Roy, rather than 9/8.
-Incineroar and Villager are swapping speed stats. Isabelle's run speed is also being raised equivalently.
-Villager and Isabelle's forward tilt, down tilt, and dash attack are now exactly the same, inheriting the strongest properties of each. This partially re-clones these fighters in order to potentially label them as Echo Fighters down the line.
-In turn, Isabelle receives a few new differences from Villager... most notably, she now experiences intense gravity and has a somewhat higher air speed and fall speed.
-Forward and back aerials will have significantly less range, and are overall weaker, but keep their full strength from start to finish.
-Neutral air will have even less endlag, allowing her to double jump after a rising short hop nair. (Villager will also receive a neutral air damage buff as well, to be equal with Isabelle's.)
-Isabelle will also receive quality of life improvements to her jab and down special:
Lloid Trap will no longer activate on its own, but Isabelle can activate it during other actions.
Jab's ability to confirm on hit into her other grounded normals will be made more consistent.

**Comment by WuBoytH** [comment]
Hi, here I am hijacking Bor's Animal Crossing Update (tm) to give a quality of life change to Daisy

- [ ] Parasol Plummet - Adjusted Knockback so the aerial hitbox is actually useful. In fact, I might just make it one hitbox that covers both ground and air opponents.
